$schema: "../gutenTAG/config/schema/guten-tag-generation-config.schema.yaml"

#############################
# Definitions
#############################
# base oscillations
base:
  - &base-ts-short
    length: 1000
    semi-supervised: true
    supervised: true
  - &base-ts
    length: 10000
    semi-supervised: true
    supervised: true

sine:
  - &sine-0
    kind: "sine"
    frequency: 0.5
    amplitude: 1.0
    variance: 0.05
  - &sine-1
    <<: *sine-0
    frequency: 0.8
    amplitude: 2.5
    offset: -2.0
    freq-mod: 0.5
  - &sine-2
    <<: *sine-0
    frequency: 0.4
    amplitude: 0.6
    offset: 1.0
  - &sine-3
    <<: *sine-0
    frequency: 0.9
    amplitude: 0.9
    offset: 1.3
    freq-mod: 0.01
  - &sine-other-trend
    <<: *sine-0
    amplitude: 2
    variance: 0.1
    trend:
      kind: "sine"
      frequency: 0.1
      amplitude: 0.5
      variance: 0
  - &sine-low-freq
    kind: "sine"
    frequency: 0.1
    amplitude: 0.5
    variance: 0.05

ecg:
  - &ecg-0
    kind: "ecg"
    frequency: 0.8
    variance: 0.05
  - &ecg-0-offset
    kind: "ecg"
    frequency: 0.8
    variance: 0.1
  - &ecg-1
    <<: *ecg-0
    frequency: 1
  - &ecg-trend
    kind: "ecg"
    frequency: 1
    variance: 0.05
    trend:
      kind: "polynomial"
      polynomial: [ 8, 4, 2, 8 ]

random-walk:
  - &rw-0
    kind: "random-walk"
    variance: 0.0
    amplitude: 1.0
  - &rw-1
    <<: *rw-0
    amplitude: 2.5
    offset: -2.0
    smoothing: 0.1
  - &rw-2
    <<: *rw-0
    amplitude: 0.5
    offset: 1.3
    variance: 0.05
  - &rw-no-smoothing
    <<: *rw-0
    smoothing: 0
    offset: 3.2
  - &rw-linear-trend
    <<: *rw-0
    amplitude: 1
    trend:
      kind: "polynomial"
      polynomial: [3, 3]
      amplitude: 2
  - &rw-other-trend
    <<: *rw-2
    trend:
      kind: "sine"
      frequency: 0.05
      amplitude: 0.25
      variance: 0

cylinder-bell-funnel:
  - &cbf-0
    kind: "cylinder-bell-funnel"
    avg-pattern-length: 100
    variance-pattern-length: 0.2
    variance-amplitude: 0.1
    amplitude: 1.0
    variance: 0.05
    offset: -3
  - &cbf-1
    <<: *cbf-0
    avg-pattern-length: 160
    variance-amplitude: 5
    offset: 12.4
  - &cbf-linear-trend
    <<: *cbf-1
    trend:
      kind: "polynomial"
      polynomial: [2, 2]
  - &cbf-other-trend
    <<: *cbf-1
    trend:
      kind: "polynomial"
      polynomial: [-8, 8, 2, -10]

polynomial:
  - &poly-0
    kind: "polynomial"
    polynomial: [-8, 8, 2, -10]
    variance: 0.05
    offset: -2
  - &poly-1
    <<: *poly-0
    polynomial: [1, 1, -8, -4, 1]
  - &poly-other-trend
    <<: *poly-0
    variance: 0.1
    offset: 34.2
    trend:
      kind: "sine"
      frequency: 0.1
      amplitude: 0.5
  - &poly-linear
    <<: *poly-0
    polynomial: [ 0.2, 0.2 ]
  - &poly-linear-strong
    <<: *poly-0
    polynomial: [ 2, 2 ]
  - &poly-quadratic
    <<: *poly-0
    polynomial: [ 0.2, 0.2, 10 ]

# anomalies
anomaly_kinds:
  - &local-extremum
    length: 1
    kinds:
      - kind: "extremum"
        min: true
        local: true
        context_window: 50
  - &global-extremum
    length: 1
    kinds:
      - kind: "extremum"
        min: false
        local: false
  - &frequency-10
    length: 10
    kinds:
      - kind: "frequency"
        frequency_factor: 2.0
  - &frequency-50
    length: 50
    kinds:
      - kind: "frequency"
        frequency_factor: 2.0
  - &mean-10
    length: 10
    kinds:
      - kind: "mean"
        offset: 0.3
  - &mean-100
    length: 100
    kinds:
      - kind: "mean"
        offset: 0.3
  - &pattern
    length: 100
    kinds:
      - kind: "pattern"
        sinusoid_k: 10.0
        cbf_pattern_factor: 2
  - &pattern-shift
    length: 100
    kinds:
      - kind: "pattern-shift"
        shift_by: 10
        transition_window: 10
  - &platform
    length: 100
    kinds:
      - kind: "platform"
        value: 0.0
  - &variance-large
    length: 100
    kinds:
      - kind: "variance"
        variance: 0.3
  - &variance-medium
    length: 100
    kinds:
      - kind: "variance"
        variance: 0.1
  - &variance-small
    length: 100
    kinds:
      - kind: "variance"
        variance: 0.03
  - &amplitude-larger
    length: 100
    kinds:
      - kind: "amplitude"
        amplitude_factor: 2
  - &amplitude-smaller
    length: 100
    kinds:
      - kind: "amplitude"
        amplitude_factor: 0.5
  - &trend-anomaly-sine
    length: 100
    kinds:
      - kind: "trend"
        oscillation:
          kind: "sine"
          frequency: 1
          amplitude: 1.0
          variance: 0.0
  - &trend-anomaly-linear
    length: 100
    kinds:
      - kind: "trend"
        oscillation:
          kind: "polynomial"
          polynomial: [0.2, 0.2]


#############################
# Time series declarations
#############################
timeseries:
  # noise
  - name: 2-sine-one-channel-anomaly-noise-00%
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-0
      variance: 0
    anomalies:
      - *platform
  - name: 2-sine-one-channel-anomaly-noise-01%
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-0
      variance: 0.01
    anomalies:
      - *platform
  - name: 2-sine-one-channel-anomaly-noise-10%
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-0
      variance: 0.10
    anomalies:
      - *platform
  - name: 2-sine-one-channel-anomaly-noise-30%
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-0
      variance: 0.30
    anomalies:
      - *platform
  - name: 2-sine-one-channel-anomaly-noise-50%
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-0
      variance: 0.50
    anomalies:
      - *platform

  # position
  - name: 2-sine-one-channel-anomaly-beginning
    <<: *base-ts
    channels: 2
    base-oscillation:
      <<: *sine-other-trend
    anomalies:
      - position: beginning
        <<: *mean-100
  - name: 2-sine-one-channel-anomaly-middle
    <<: *base-ts
    channels: 2
    base-oscillation:
      <<: *sine-other-trend
    anomalies:
      - position: middle
        <<: *mean-100

  - name: 2-sine-short-5-anomalies-one-channel
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      <<: *sine-2
    anomalies:
      - position: middle
        <<: *frequency-10
      - position: middle
        <<: *frequency-10
      - position: end
        <<: *frequency-10
      - position: end
        <<: *frequency-10
      - position: end
        <<: *frequency-10
  - name: 2-sine-long-5-anomalies-one-channel
    <<: *base-ts
    channels: 2
    base-oscillation:
      <<: *sine-2
    anomalies:
      - position: middle
        <<: *frequency-50
      - position: middle
        <<: *frequency-50
      - position: end
        <<: *frequency-50
      - position: end
        <<: *frequency-50
      - position: end
        <<: *frequency-50

  - name: 2-sine-long-2-diff-anomalies-one-channel
    <<: *base-ts
    channels: 2
    base-oscillation:
      *sine-1
    anomalies:
      - position: middle
        <<: *frequency-50
      - position: end
        <<: *pattern
  - name: 4-sine-long-9-diff-anomalies-one-channel
    <<: *base-ts
    channels: 4
    base-oscillations:
      - *sine-0
      - *sine-1
      - *sine-2
      - *sine-3
    anomalies:
      - position: beginning
        <<: *pattern-shift
      - position: beginning
        <<: *mean-100
      - position: middle
        <<: *frequency-50
      - position: middle
        <<: *pattern
      - position: middle
        <<: *amplitude-smaller
      - position: end
        <<: *global-extremum
      - position: end
        <<: *variance-large
      - position: end
        <<: *platform
      - position: end
        <<: *trend-anomaly-sine

#   channels
  - name: 4-sine-all-channel-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillations:
      - *sine-0
      - *sine-1
      - *sine-2
      - *sine-3
    anomalies:
      - exact-position: 950
        channel: 0
        <<: *frequency-10
      - exact-position: 900
        channel: 1
        <<: *frequency-10
      - exact-position: 960
        channel: 2
        <<: *frequency-10
      - exact-position: 880
        channel: 3
        <<: *frequency-10
  - name: 2-sine-one-channel-frequency-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillations:
      - *sine-1
      - *sine-2
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-10
  - name: 2-sine-one-channel-mean-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillations:
      - *sine-2
      - *sine-3
    anomalies:
      - position: middle
        channel: 1
        <<: *mean-10
  - name: 3-sine-one-channel-anomaly
    <<: *base-ts-short
    base-oscillations:
      - *sine-2
      - *sine-0
      - *sine-1
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-10
  - name: 2-sine-all-channel-anomaly
    <<: *base-ts-short
    base-oscillations:
      - *sine-other-trend
      - *sine-0
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-10
      - position: middle
        channel: 1
        <<: *frequency-10

# For ecg base
#############################
  - name: 2-ecg-one-channel-anomaly
    <<: *base-ts-short
    length: 3000
    channels: 2
    base-oscillations:
      - *ecg-0
      - *ecg-0-offset
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-50
  - name: 8-ecg-one-channel-anomaly
    <<: *base-ts-short
    length: 3000
    channels: 8
    base-oscillation:
      *ecg-0
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-50
  - name: 6-ecg-one-channel-anomaly
    <<: *base-ts-short
    channels: 6
    base-oscillation:
      *ecg-1
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-10
  - name: 2-ecg-all-channel-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *ecg-0-offset
    anomalies:
      - position: middle
        channel: 0
        <<: *frequency-10
      - position: end
        channel: 1
        <<: *frequency-10
  - name: 6-ecg-one-channel-pattern-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *ecg-1
    anomalies:
      - position: middle
        channel: 0
        length: 50
        <<: *pattern
  - name: 4-ecg-one-channel-amplitude-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *ecg-1
    anomalies:
      - position: middle
        channel: 1
        length: 50
        <<: *amplitude-smaller
      - position: end
        channel: 3
        length: 50
        <<: *amplitude-smaller

# For CBF base
#############################
  - name: 4-cbf-all-channel-anomaly
    <<: *base-ts-short
    length: 2000
    channels: 4
    base-oscillation:
      *cbf-1
    anomalies:
      - exact-position: 900
        channel: 0
        length: 50
        <<: *mean-10
      - exact-position: 980
        channel: 1
        length: 50
        <<: *mean-10
      - exact-position: 1100
        length: 50
        channel: 2
        <<: *mean-10
      - exact-position: 1500
        channel: 3
        length: 50
        <<: *mean-10
  - name: 2-cbf-one-channel-middle-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *cbf-1
    anomalies:
      - position: middle
        channel: 0
        length: 30
        <<: *mean-10
  - name: 6-cbf-one-channel-anomaly
    <<: *base-ts-short
    channels: 6
    base-oscillation:
      *cbf-1
    anomalies:
      - position: middle
        channel: 0
        <<: *mean-10
  - name: 2-cbf-one-channel-short-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *cbf-1
    anomalies:
      - position: middle
        channel: 0
        <<: *mean-10
  - name: 2-cbf-all-channel-middle-extremum-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *cbf-1
    anomalies:
      - position: middle
        channel: 1
        <<: *local-extremum
      - position: end
        channel: 0
        <<: *global-extremum
  - name: 2-cbf-one-channel-middle-trend-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *cbf-1
    anomalies:
      - position: middle
        channel: 1
        <<: *trend-anomaly-sine


# For random walk base
#############################
  - name: 4-rw-all-channels-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *rw-1
    anomalies:
      - exact-position: 500
        channel: 0
        <<: *mean-10
      - exact-position: 500
        channel: 1
        <<: *mean-10
      - exact-position: 500
        channel: 2
        <<: *mean-10
      - exact-position: 500
        channel: 3
        <<: *mean-10
  - name: 2-rw-one-channels-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 0
        <<: *mean-10
  - name: 6-rw-one-channels-anomaly
    <<: *base-ts-short
    channels: 6
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 0
        <<: *mean-10
  - name: 10-rw-one-channels-anomaly
    <<: *base-ts-short
    channels: 10
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 0
        <<: *mean-10
  - name: 2-rw-one-channels-platform-anomaly
    <<: *base-ts-short
    channels: 2
    base-oscillation:
      *rw-1
    anomalies:
      - exact-position: 700
        channel: 0
        <<: *platform
  - name: 4-rw-one-channels-extremum-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 3
        <<: *local-extremum
  - name: 4-rw-one-channels-variance-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 3
        length: 150
        <<: *variance-medium
  - name: 2-rw-one-channels-trend-anomaly
    <<: *base-ts-short
    channels: 4
    base-oscillation:
      *rw-1
    anomalies:
      - position: middle
        channel: 3
        length: 100
        <<: *trend-anomaly-sine
